spring.application.name=training_refactoring

spring.datasource.url=jdbc:postgresql://localhost:5432/f1_db
spring.datasource.username=f1_user
spring.datasource.password=secretpassword
spring.jpa.hibernate.ddl-auto=update
