INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 1, 1, 'Red Bull Racing', 'Italy', 'Max Verstappen', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 2, 2, 'Mercedes', 'Italy', 'Lewis Hamilton', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 3, 3, 'Mercedes', 'Italy', 'Valtteri Bottas', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 4, 4, 'McLaren', 'Italy', 'Lando Norris', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 5, 5, 'Red Bull Racing', 'Italy', 'Sergio Perez', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 1, 6, 'Red Bull Racing', 'Italy', 'Max Verstappen', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 2, 7, 'Mercedes', 'Italy', 'Lewis Hamilton', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 3, 8, 'Mercedes', 'Italy', 'Valtteri Bottas', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 4, 9, 'McLaren', 'Italy', 'Lando Norris', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-04-18', 5, 10, 'Red Bull Racing', 'Italy', 'Sergio Perez', 'Autodromo Enzo e Dino Ferrari');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-02', 1, 11, 'Mercedes', 'Portugal', 'Lewis Hamilton', 'Autódromo Internacional do Algarve');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-02', 2, 12, 'Red Bull Racing', 'Portugal', 'Max Verstappen', 'Autódromo Internacional do Algarve');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-02', 3, 13, 'Mercedes', 'Portugal', 'Valtteri Bottas', 'Autódromo Internacional do Algarve');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-02', 4, 14, 'Red Bull Racing', 'Portugal', 'Sergio Perez', 'Autódromo Internacional do Algarve');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-02', 5, 15, 'McLaren', 'Portugal', 'Lando Norris', 'Autódromo Internacional do Algarve');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-09', 1, 16, 'Mercedes', 'Spain', 'Lewis Hamilton', 'Circuit de Barcelona-Catalunya');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-09', 2, 17, 'Red Bull Racing', 'Spain', 'Max Verstappen', 'Circuit de Barcelona-Catalunya');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-09', 3, 18, 'Mercedes', 'Spain', 'Valtteri Bottas', 'Circuit de Barcelona-Catalunya');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-09', 4, 19, 'Red Bull Racing', 'Spain', 'Sergio Perez', 'Circuit de Barcelona-Catalunya');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-09', 5, 20, 'McLaren', 'Spain', 'Lando Norris', 'Circuit de Barcelona-Catalunya');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-23', 1, 21, 'Red Bull Racing', 'Monaco', 'Max Verstappen', 'Circuit de Monaco');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-23', 2, 22, 'Mercedes', 'Monaco', 'Lewis Hamilton', 'Circuit de Monaco');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-23', 3, 23, 'Ferrari', 'Monaco', 'Carlos Sainz', 'Circuit de Monaco');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-23', 4, 24, 'McLaren', 'Monaco', 'Lando Norris', 'Circuit de Monaco');
INSERT INTO public.f1_races (date, position, id, car, country, driver, track) VALUES ('2021-05-23', 5, 25, 'Mercedes', 'Monaco', 'Valtteri Bottas', 'Circuit de Monaco');
